### PR TITLE
Add fevicon to the site

### PR DESCRIPTION
**Pull request by Sandigupta**
Please merge this PR.

### CODE REVIEW

**Comment by Sandigupta** [comment]
@Vinit710 Please merge this PR to avoid conflicts.

**Comment by Sandigupta** [comment]
@Vinit710 Please merge this PR; otherwise, conflicts will be created.

**Review by Vinit710 — APPROVED** [review]
look good

**Comment by Sandigupta** [comment]
@Vinit710 thank you.

**Pull request merged**
