### PR TITLE
[BUG FIX] Made the Home Page responsive.

### PR DESCRIPTION
**Pull request by rishicds**
Resolves issue #19 

Before
image

After
image

Entire homepage is now responsive

### CODE REVIEW

**Review by Vinit710 — CHANGES_REQUESTED** [review]
the navbar buttons are not funtional

**Comment by rishicds** [comment]
@Vinit710 added please check

**Comment by Vinit710** [comment]
please resolve the conflicts and raise the pr again

**Comment by Vinit710** [comment]
i will merge, its correct

**Pull request closed without merging**
